### ISSUE TITLE
Update DTOs wont work

### ISSUE THREAD

**Issue by srdjo** [NetCoreTemplates/vue-nuxt#10]
Hi, 

I am trying to update DTOs but it wont work.

This is the output I get

PS C:\Project> npm run dtos

> projectvue@1.0.0 dtos C:\Project
> cd src/shared && x typescript && tsc -m ES6 dtos.ts

Could not update ServiceStack Reference 'C:\Project\src\shared\dtos.ts':
One or more errors occurred. (The SSL connection could not be established, see inner exception.)

What might be the problem ?

**Comment by mythz** [comment]
Is the project running? i.e.

    $ npm run build
    $ dotnet run

Where you can view the Web App at: https://localhost:5001

After it's running you can generate the dtos with:

    $ npm run dtos

**Comment by srdjo** [comment]
Yes, I did run both commands and I can access my app at https://localhost:5001 but I still get an error

Could not update ServiceStack Reference 'C:\Project\src\shared\dtos.ts':
One or more errors occurred. (The SSL connection could not be established, see inner exception.)

**Comment by mythz** [comment]
If your app is running at https://localhost:5001 then it should be able to generate the dtos which are just being downloaded from https://localhost:5001/types/typescript

Maybe you have an issue with your [localhost development self-signed certificate](https://www.hanselman.com/blog/DevelopingLocallyWithASPNETCoreUnderHTTPSSSLAndSelfSignedCerts.aspx), can you try running:

    $ dotnet dev-certs https --trust

Then re-running the server i.e. `dotnet run` and seeing if you can generate the dtos `npm run dtos`.

**Comment by srdjo** [comment]
That was it. Works like a charm now.

Thanks a lot

**Comment by mythz** [comment]
Great, happy to hear it 👍
