### ISSUE TITLE
 Navbar does not work with nested menu items, added to the appsettings.json

### ISSUE THREAD

**Issue by laitang2000** [NetCoreTemplates/vue-nuxt#13]
Generating a new project via cli and then modifying the navitems config show below

``` 
"NavItems": [
    { "href":"/",         "label": "Home", "exact":true },
    { "href":"/about",    "label": "About" },
    { "href":"/signin",   "label": "Sign In",  "hide":"auth" },
    { "href":"/profile",  "label": "Profile",  "show":"auth" },
    { "href":"/contact",            "label":"Contact",
      "children": [
        { "href": "/contact/me",    "label":"Me" },
        { "href": "/contact/email", "label":"Email" },
        { "label":"-" },
        { "href": "/contact/phone", "label":"Phone" }
      ]
    }
  ]
```

the nav bar does not display the child nav items

**Comment by mythz** [comment]
The click to display functionality isn't supported as that would require [bootstrap.js, jQuery & Popper.js](https://getbootstrap.com/) which I don't want to include as jQuery is an outdated heavy dependency in SPA templates.

But I've resolved an issue with `@servicestack/vue` Navbar rendering and added a display on hover in [this commit](https://github.com/NetCoreTemplates/vue-nuxt/commit/e7a4a10a39a1839b8f20a9704464b21288e52199):

```css
.nav-item.dropdown:hover .dropdown-menu {
  display: block;
}
```

Which is available in new project templates:

    $ x new vue-nuxt ProjectName

Which will now display nested menus on hover:

![image](https://user-images.githubusercontent.com/89361/93023246-44b01c00-f620-11ea-9792-215d46632bac.png)

**Comment by laitang2000** [comment]
Perfect thanks :)
