### ISSUE TITLE
npm run dtos -  error 

### ISSUE THREAD

**Issue by laitang2000** [NetCoreTemplates/vue-nuxt#15]
using the latest template command from cli and running npm run dtos fails with the following error message :

$ npm run dtos

> latest@1.0.0 dtos C:\Dev\latestnuxt\latest\latest
> cd src/shared && x typescript && tsc -m ES6 dtos.ts

Updated: dtos.ts
../../node_modules/@types/uglify-js/index.d.ts:9:30 - error TS2307: Cannot find module 'source-map' or its corresponding type declarations.

9 import { RawSourceMap } from 'source-map';
                               ~~~~~~~~~~~~

../../node_modules/@types/webpack-sources/index.d.ts:11:62 - error TS2307: Cannot find module 'source-map' or its corresponding type declarations.

11 import { SourceNode, RawSourceMap, SourceMapGenerator } from 'source-map';
                                                                ~~~~~~~~~~~~

../../node_modules/@types/webpack/index.d.ts:46:30 - error TS2307: Cannot find module 'source-map' or its corresponding type declarations.

46 import { RawSourceMap } from 'source-map';
                                ~~~~~~~~~~~~


Found 3 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! latest@1.0.0 dtos: `cd src/shared && x typescript && tsc -m ES6 dtos.ts`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the latest@1.0.0 dtos script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by mythz** [comment]
This was a new issue with the latest uglify version, need to remove `-m ES6` from the **dtos** npm script, e.g: 

```json
    "dtos": "cd src/shared && x typescript && tsc dtos.ts",
```

This is change is in the latest version:

    $ x new vue-nuxt ProjectName

**Comment by laitang2000** [comment]
Thanks
