### ISSUE TITLE
Clarify "Dev Workflow" commands

### ISSUE THREAD

**Issue by wcwhitehead** [NetCoreTemplates/vue-nuxt#16]
Assuming the user has followed the installation instructions up to this point, starting a watched dotnet build command should probably be:
`$ dotnet watch --project <ProjectName> run`

Also, might be helpful to note that user should be in the 'ProjectName' folder (from the project root) when running the `$ npm run dev` command.

**Comment by mythz** [comment]
It's already mentioned:

> After creating your project go to your `ProjectName` folder 

It's standard for all .NET and node projects to run the Host project when you want to run (or watch) an App, specifying the project name is unnecessary.
