### ISSUE TITLE
Migrate build from gulp to webpack

### ISSUE THREAD

**Issue by ariellephan** [NetCoreTemplates/vue-nuxt#2]
Vue CLI comes with webpack by default so the migration is encouraged.

**Comment by mythz** [comment]
Everything is already powered by Webpack, the [gulpfile](https://github.com/NetCoreTemplates/vue-nuxt/blob/master/MyApp/gulpfile.js) is just a wrapper around running npm scripts so they can be executed from within VS.NET GUI Task Runner Explorer, as documented in the [Webpack powered SPA Template docs](http://docs.servicestack.net/templates-single-page-apps).
