### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by jleu3482** [NetCoreTemplates/vue-nuxt#39]
I can't find which folder the database is installed and the type of database being used.

**Comment by mythz** [comment]
This project doesn't use a Database, you can add your preferred database with [mix scripts](https://docs.servicestack.net/ormlite/installation#quick-install-in-asp.net-core-with-mix) or select the RDBMS you want to use when creating the template on ServiceStack's start page:

### https://servicestack.net/start
