### ISSUE TITLE
I do not work in iis

### ISSUE THREAD

**Issue by itoop2019** [NetCoreTemplates/vue-nuxt#5]
I do according to the README.md tool. Dev-environment - works. I do npm run publish and deploy to IIS, but the application seems to start up, but the circle is spinning all the time and nothing happens
![MyApp-Nuxt](https://user-images.githubusercontent.com/47772383/60340760-2a573780-99b5-11e9-92fd-f90df98e39cf.jpg)

**Comment by mythz** [comment]
Please provide as much info you can about the error. 

e.g. Does Chrome Web Inspector show any error network requests? What is the full Request/Response Headers of requests that have failed.

Does it have any JavaScript errors? etc.

**Comment by mythz** [comment]
Also make sure that your published App works locally, i.e. in your publish folder:

   $ cd bin\Release\netcoreapp2.1\publish

Run your Host project dll, e.g:

   $ dotnet YourProjectName.dll

**Comment by itoop2019** [comment]
Sorry.
I think what the problem is.

If you create a non-nested application in IIS, then everything works fine.
But I in IIS created an application internal (or nested, in pic)

![IISnuxtNested](https://user-images.githubusercontent.com/47772383/60356346-69977f80-99d9-11e9-9393-4bebbf8aa71c.jpg)

So, if you do the nested, then the web api works, 

![IISnuxtNestedAPI](https://user-images.githubusercontent.com/47772383/60356736-6a7ce100-99da-11e9-817d-764809337295.jpg)



but the front - does not work

![IISnuxtNestedPath](https://user-images.githubusercontent.com/47772383/60356497-cf840700-99d9-11e9-8a4f-47a354c9a0e0.jpg)

**Comment by mythz** [comment]
The nested path is breaking paths in Nuxt's generated pages which expects it to be available from the `/` path, e.g. `/wwwroot/_nuxt` should be available from `/_nuxt` which Nuxt hard codes in all its generated pages.

The way to control how Nuxt generates its pages is via [generate configuration in nuxt.config.js](https://github.com/NetCoreTemplates/vue-nuxt/blob/master/MyApp/nuxt.config.js#L4), the documentation for [Nuxt's generate configuration is here](https://nuxtjs.org/api/configuration-generate) but there doesn't seem to be any configuration to control the base path for its generated resources so it doesn't look like it supports not hosting it from `/` root path. 

If you wanted to host it from a virtual path in IIS you're going to need to configure a reverse proxy or rewrite rules in front of your App that rewrites paths into what Nuxt expects.
