### ISSUE TITLE
Data fetching

### ISSUE THREAD

**Issue by srdjo** [NetCoreTemplates/vue-nuxt#9]
Is there anywhere an example of how to consume ServiceStack API from Nuxt.js ?

I am trying to get links from getLinks with no luck

Like on this [example ](http://vue-nuxt.web-templates.io/contact)

**Comment by srdjo** [comment]
I came up with this

`<script>
  import { mapGetters } from "vuex";
  import { getLinks } from "~/shared/gateway";

  export default {
    components: {
    },

    data: () => ({
      links: [],
    }),



    computed: {
      ...mapGetters(["userSession"])
    },

    async mounted() {
      this.name = 'Nuxt';
      this.links = await getLinks();

    }
  }</script>`

**Comment by mythz** [comment]
Here's an example in this template in [/pages/index.vue](https://github.com/NetCoreTemplates/vue-nuxt/blob/ea3b7eedb8e409e2a514efd8e6657017d0b3def5/MyApp/src/pages/index.vue#L57-L59):

```js
import { hello } from "~/shared/gateway";
//...

this.result = newName
    ? await hello(newName)
    : ''
```

From [/shared/gateway.js](https://github.com/NetCoreTemplates/vue-nuxt/blob/master/MyApp/src/shared/gateway.js)

````js
import { JsonServiceClient, GetNavItems } from "@servicestack/client";
import { Hello, GetLinks, GetPost, Authenticate } from "./dtos";

export const client = new JsonServiceClient("/");

export const hello = async (name) => (await client.get(new Hello({ name }))).result;
```
